version: "3.7"
services:
  poseidon-service:
    build: .
    container_name: poseidon-service
    image: poseidon-service
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: poseidon-db
      MYSQL_PORT: 3306
      VAULT_HOST: poseidon-vault
    depends_on:
      - poseidon-db
      - poseidon-vault

  poseidon-db:
    image: "mysql:latest"
    container_name: poseidon-db
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: poseidon
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./doc/data.sql:/docker-entrypoint-initdb.d/data.sql
    depends_on:
      - poseidon-vault

  poseidon-vault:
    image: "hashicorp/vault:latest"
    restart: on-failure
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8200'
      VAULT_ADDR: 'http://0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    container_name: poseidon-vault